# app/config/security.yml
security:
    encoders:
            FOS\UserBundle\Model\UserInterface: bcrypt
    role_hierarchy:
            ROLE_COUPLE:      ROLE_USER
            ROLE_PRESTATAIRE: ROLE_USER
            ROLE_ADMIN:       ROLE_ADMIN
            ROLE_SUPER_ADMIN: ROLE_SUPER_ADMIN
    providers:
            fos_userbundle:
                id: fos_user.user_provider.username_email
    firewalls:
            api_doc:
                pattern: ^/api/doc
                security: false

            api_login:
                pattern:  ^/login
                stateless: true
                anonymous: true
                form_login:
                    check_path:               /login
                    username_parameter:       username
                    password_parameter:       password
                    success_handler:          lexik_jwt_authentication.handler.authentication_success
                    failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                    require_previous_session: false

            api_register:
                        pattern: ^/register
                        anonymous: true

            api_password_reset:
                        pattern: ^/password/reset
                        anonymous: true
            api:
                pattern:   ^/
                stateless: true
                provider: fos_userbundle
                guard:
                    authenticators:
                            - lexik_jwt_authentication.jwt_token_authenticator
               #   lexik_jwt: ~

            # main:
              #   pattern: ^/
               #  form_login:
                 #    login_path: fos_user_security_login
                  #   check_path: fos_user_security_check
    #                default_target_path: /administration/association
                  #   provider: fos_userbundle
                 #    csrf_token_generator: security.csrf.token_manager

                    # if you are using Symfony < 2.8, use the following config instead:
                    # csrf_provider: form.csrf_provider
                # logout:
                #     path:   /logout
                 #    target: /login #This is home url
               #  anonymous:    true

    access_control:
            - { path: ^/login$,           role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register$,        role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/password/reset,   role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/profile$ ,        role: IS_AUTHENTICATED_FULLY }
            - { path: ^/password/change,  role: IS_AUTHENTICATED_FULLY }
            - { path: ^/admin ,           role: ROLE_ADMIN }
            - { path: ^/list_villes ,     role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/,                 roles: IS_AUTHENTICATED_FULLY }


            #- { path: ^/, role: ROLE_USER }