<?php

namespace SW\PrestataireBundle\Repository;
use Doctrine\ORM\QueryBuilder;

/**
 * AvisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvisRepository extends \Doctrine\ORM\EntityRepository
{
    public function AvisCouple($couple)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->where('a.couple= :id')
            ->setParameter('id', $couple)
        ;
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
    public function AvisPrestataire($prestataire)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->where('a.prestataire= :id')
            ->setParameter('id', $prestataire)
            ->select('SUM(a.avis)/count(a)')
        ;

        return $qb
            ->getQuery()
            ->getSingleScalarResult()
            ;
    }

    public function NbAvisPrestataire($prestataire)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->where('a.prestataire= :id')
            ->setParameter('id', $prestataire)
            ->select('count(a)')
        ;

        return $qb
            ->getQuery()
            ->getSingleScalarResult()
            ;
    }
}
