<?php

namespace SW\PrestataireBundle\Repository;

/**
 * ContactPersonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactPersonneRepository extends \Doctrine\ORM\EntityRepository
{
}
