<?php

namespace SW\PrestataireBundle\Repository;
use Doctrine\ORM\QueryBuilder;
/**
 * CoupleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoupleRepository extends \Doctrine\ORM\EntityRepository
{
    public function showCoupleByIdUser($user)
    {
        $qb = $this->createQueryBuilder('co');

        $qb->where('co.id_user= :id')
            ->setParameter('id', $user)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
