<?php

namespace SW\PrestataireBundle\Repository;
use Doctrine\ORM\QueryBuilder;
/**
 * DiscussionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscussionRepository extends \Doctrine\ORM\EntityRepository
{
    public function listDiscussion_By_Prestataire($prestataire)
    {
        $qb = $this->createQueryBuilder('dis');


        $qb->where('dis.prestataire= :id')
            ->setParameter('id', $prestataire)
            ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
    public function listDiscussion_By_Couple($couple)
    {
        $qb = $this->createQueryBuilder('dis');


        $qb->where('dis.couple= :id')
            ->setParameter('id', $couple)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
    public function NbDiscussion_By_Prestataire($prestataire)
    {
        $qb = $this->createQueryBuilder('dis');

        $qb->where('dis.prestataire= :id')
            ->setParameter('id', $prestataire)
            ->select('count(dis)')
        ;

        return $qb
            ->getQuery()
            ->getSingleScalarResult()
            ;
    }
    public function NbDiscussion_By_Couple($couple)
    {
        $qb = $this->createQueryBuilder('dis');

        $qb->where('dis.couple= :id')
            ->setParameter('id', $couple)
            ->select('count(dis)')
        ;

        return $qb
            ->getQuery()
            ->getSingleScalarResult()
            ;
    }
}
