<?php

namespace SW\PrestataireBundle\Repository;
use Doctrine\ORM\QueryBuilder;
/**
 * DisponibiliteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisponibiliteRepository extends \Doctrine\ORM\EntityRepository
{
    public function listDisponibilite_By_Prestataire($prestataire)
    {
        $qb = $this->createQueryBuilder('d');

        $qb->where('d.prestataire= :id')
            ->setParameter('id', $prestataire)
            ->select('d.dateDebut,d.dateFin,d.note')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
    public function deleteDisponibilite_By_Prestataire($prestataire)
    {
        $qb = $this->createQueryBuilder('d');

        $qb->where('d.prestataire= :id')
            ->setParameter('id', $prestataire)
            ->delete('')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
