<?php

namespace SW\PrestataireBundle\Repository;
use Doctrine\ORM\QueryBuilder;
/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{
    public function listEvenements_By_Prestataire($prestataire)
    {
        $qb = $this->createQueryBuilder('e');

        $qb->where('e.prestataire= :id')
            ->setParameter('id', $prestataire)
            ->select('e.id,e.nom,e.type,e.dateDebut,e.dateFin,e.ville,e.adresse,e.description,e.image')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
    public function listEvenements_By_Ville($ville)
    {
        $qb = $this->createQueryBuilder('e');

        $qb->where('e.ville= :ville')
            ->setParameter('ville', $ville)
            ->select('e.id,e.nom,e.type,e.dateDebut,e.dateFin,e.ville,e.adresse,e.description,e.image')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
    public function deleteEvenement_By_Prestataire($id)
    {
        $qb = $this->createQueryBuilder('li');

        $qb->where('li.prestataire= :id')
            ->setParameter('id', $id)
            ->delete('')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
