<?php

namespace SW\PrestataireBundle\Repository;
use Doctrine\ORM\QueryBuilder;
/**
 * FicheInformationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheInformationsRepository extends \Doctrine\ORM\EntityRepository
{
    public function showFicheInformations_By_SousCatgorie($id)
    {
        $qb = $this->createQueryBuilder('fi');

        $qb->where('fi.sousCategorie= :id')
            ->setParameter('id', $id)
            ->select('')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

    public function idFicheInformations_By_SousCatgorie($id)
    {
        $qb = $this->createQueryBuilder('fi');

        $qb->where('fi.sousCategorie= :id')
            ->setParameter('id', $id)
            ->select('fi.id')
        ;

        return $qb
            ->getQuery()
            ->getSingleScalarResult()
            ;
    }
}
