<?php

namespace SW\PrestataireBundle\Repository;
use Doctrine\ORM\QueryBuilder;
/**
 * GalerieVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalerieVideoRepository extends \Doctrine\ORM\EntityRepository
{
    public function listGalerieVideo_By_Prestataire($id)
    {
        $qb = $this->createQueryBuilder('gv');

        $qb->where('gv.prestataire= :id')
            ->setParameter('id', $id)
            ->select('gv.id,gv.titre')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
    public function GalerieVideo_By_Prestataire_Titre($id,$titre)
    {
        $qb = $this->createQueryBuilder('gv');

        $qb->where('gv.prestataire= :id')
            ->setParameter('id', $id)
            ->andWhere('gv.titre= :titre')
            ->setParameter('titre',$titre)
            ->select('gv.id,gv.titre')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
    public function listIdGalerieVideo_By_Prestataire($id)
    {
        $qb = $this->createQueryBuilder('gv');

        $qb->where('gv.prestataire= :id')
            ->setParameter('id', $id)
            ->select('gv.id')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

}
