<?php

namespace SW\PrestataireBundle\Repository;

/**
 * InformationSpecifiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformationSpecifiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
