<?php

namespace SW\PrestataireBundle\Repository;
use Doctrine\ORM\QueryBuilder;
/**
 * LigneMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneMessageRepository extends \Doctrine\ORM\EntityRepository
{
    public function listMessages_By_Discussion($discussion)
    {
        $qb = $this->createQueryBuilder('lm');


        $qb->where('lm.discussion= :id')
            ->setParameter('id', $discussion)
            ->orderBy('lm.dateEnvoie')
            ->select('lm.id,lm.pseudo,lm.contenue,lm.destinataire,lm.expediteur,lm.dateEnvoie,lm.vue')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
    public function nbMessages_nonLu($id,$discussion)
    {
        $qb = $this->createQueryBuilder('lm');

        $qb->where('lm.destinataire= :id')
            ->setParameter('id', $id)
            ->andWhere('lm.discussion= :dis')
            ->setParameter('dis',$discussion)
            ->andWhere('lm.vue= :vu')
            ->setParameter('vu',false)
            ->select('count(lm)')
        ;

        return $qb
            ->getQuery()
            ->getSingleScalarResult()
            ;
    }
    public function updateVue($id,$discussion)
    {
        $qb = $this->createQueryBuilder('lm');

          $qb->update('SWPrestataireBundle:LigneMessage','lm')
            ->set('lm.vue', true)
              ->where('lm.destinataire= :id')
              ->setParameter('id', $id)
              ->andWhere('lm.discussion= :dis')
              ->setParameter('dis',$discussion)
            ->getQuery()->execute()
            ;
    }
}
