<?php

namespace SW\PrestataireBundle\Repository;
use Doctrine\ORM\QueryBuilder;
/**
 * ListeInvitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListeInvitesRepository extends \Doctrine\ORM\EntityRepository
{
    public function listInvites_By_Couple($couple)
    {
        $qb = $this->createQueryBuilder('l');

        $qb->where('l.couple= :id')
            ->setParameter('id', $couple)
            ->select('l.id,l.nom,l.prenom,l.email')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
