<?php

namespace SW\PrestataireBundle\Repository;
use Doctrine\ORM\QueryBuilder;
/**
 * PrestataireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrestataireRepository extends \Doctrine\ORM\EntityRepository
{
    public function listPrestataire_By_SousCategorie($id)
    {
        $qb = $this->createQueryBuilder('p');

        $qb->where('p.sousCategorie= :id')
            ->setParameter('id', $id)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
    public function showPrestataireByIdUser($id)
    {
        $qb = $this->createQueryBuilder('p');

        $qb->where('p.id_user= :id')
            ->setParameter('id', $id)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
    public function listPrestataire_By_Ville($id)
    {
        $qb = $this->createQueryBuilder('p');

        $qb->where('p.ville= :id')
            ->setParameter('id', $id)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
    public function listPrestataire_By_Ville_SousCategorie($ville,$souscategorie)
    {
        $qb = $this->createQueryBuilder('p');

        $qb->where('p.ville= :idv')
            ->setParameter('idv', $ville)
            ->andWhere('p.sousCategorie= :idsc')
            ->setParameter('idsc',$souscategorie)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

}
