<?php

namespace SW\PrestataireBundle\Repository;
use Doctrine\ORM\QueryBuilder;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function listReservation_By_Prestataire($id)
    {
        $qb = $this->createQueryBuilder('r');

        $qb->where('r.prestataire= :id')
            ->setParameter('id', $id)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

    public function listReservation_By_Couple($couple)
    {
        $qb = $this->createQueryBuilder('r');

        $qb->where('r.couple= :id')
            ->setParameter('id', $couple)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
