<?php

namespace SW\PrestataireBundle\Repository;
use Doctrine\ORM\QueryBuilder;
/**
 * ValeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValeurRepository extends \Doctrine\ORM\EntityRepository
{
    public function listValeurs_By_InformationSpecifique($id)
    {
        $qb = $this->createQueryBuilder('val');

        $qb->where('val.informationSpecifiques= :id')
            ->setParameter('id', $id)
            ->select('val.id,val.valeur,val.pardefaut')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
