<?php

namespace SW\PrestataireBundle\Repository;
use Doctrine\ORM\QueryBuilder;
/**
 * VilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VilleRepository extends \Doctrine\ORM\EntityRepository
{
    public function listVille_By_Pays($id)
    {
        $qb = $this->createQueryBuilder('v');

        $qb->where('v.pays= :id')
            ->setParameter('id', $id)
            ->select('v.nom')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
